name: universal_webview
version: 1.0.0+1
publish_to: none
description: Flutter applciation with Webview and Notifications.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.2.1+1
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  in_app_review: ^2.0.9

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


